services:
  scrapyd:
    build: .
    ports:
      - "6800:6800"
    volumes:
      # Map eggs, logs, and db directories to host directories for persistence
      - ./scrapyd/eggs:/var/lib/scrapyd/eggs
      - ./scrapyd/logs:/var/log/scrapyd
      - ./scrapyd/dbs:/var/lib/scrapyd/dbs
    restart: always
